N-Tier.MiniApp.Presentation.WebUI/Controllers/SirketlerController.cs
using N_Tier.MiniApp.Presentation.WebUI.ViewModels;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace N_Tier.MiniApp.Presentation.WebUI.Controllers
{
    public class SirketlerController : Controller
    {
        readonly string apiBaseAddress = ConfigurationManager.AppSettings["apiBaseAdress"];

        public async Task<ActionResult> Index()
        {
            
            IEnumerable<SirketViewModel> sirkets = null;

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(apiBaseAddress);

                var httpResponse = await client.GetAsync("Sirket");

                if (httpResponse.IsSuccessStatusCode)
                {
                    sirkets = await httpResponse.Content.ReadAsAsync<IList<SirketViewModel>>();
                    
                }
                else
                {
                    sirkets = Enumerable.Empty<SirketViewModel>();
                    ModelState.AddModelError(string.Empty, "Server error.");
                }
            }

            return View(sirkets);
        }

        public async Task<ActionResult> Details(int Id)
        {

            SirketViewModel sirket = null;
            string imgBase64Data = "";
            string imgDataURL = "";

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(apiBaseAddress);

                var httpResponse = await client.GetAsync($"Sirket/{Id}");

                if (httpResponse.IsSuccessStatusCode)
                {
                    sirket = await httpResponse.Content.ReadAsAsync<SirketViewModel>();
                    imgBase64Data = Convert.ToBase64String(sirket.Logo);
                    imgDataURL = string.Format("data:image/png;base64,{0}", imgBase64Data);
                    ViewBag.ImageData = imgDataURL;
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error.");
                }
            }

            if (sirket == null)
            {
                return HttpNotFound();
            }

            return View(sirket);

        }

        public async Task<ActionResult> Edit(int id)
        {
            SirketViewModel sirket = null;
            string imgBase64Data = "";
            string imgDataURL = "";
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(apiBaseAddress);

                var httpResponse = await client.GetAsync($"Sirket/{id}");

                if (httpResponse.IsSuccessStatusCode)
                {
                    sirket = await httpResponse.Content.ReadAsAsync<SirketViewModel>();
                    imgBase64Data = Convert.ToBase64String(sirket.Logo);
                    imgDataURL = string.Format("data:image/png;base64,{0}", imgBase64Data);
                    ViewBag.ImageData = imgDataURL;
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error.");
                }
            }
            if (sirket == null)
            {
                return HttpNotFound();
            }
            return View(sirket);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(int id, CreateSirketViewModel sirketResource)
        {
            var file = Request.Files["Image"];
            if (file != null)
            {
                byte[] fileBytes = new byte[file.ContentLength];
                file.InputStream.Read(fileBytes, 0, file.ContentLength);
                sirketResource.Logo = fileBytes;
            }
            else
            {
                // TO-DO: Error handling
            }

            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(apiBaseAddress);
                    var httpResponse = await client.PutAsJsonAsync($"Sirket/{id}", sirketResource);
                    if (httpResponse.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Server error try after some time.");
                    }
                }
                return RedirectToAction("Index");
            }
            return View(sirketResource);
        }

        public async Task<ActionResult> Delete(int id)
        {
            SirketViewModel sirket = null;
            string imgBase64Data = "";
            string imgDataURL = "";

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(apiBaseAddress);

                var httpResponse = await client.GetAsync($"Sirket/{id}");

                if (httpResponse.IsSuccessStatusCode)
                {
                    sirket = await httpResponse.Content.ReadAsAsync<SirketViewModel>();
                    imgBase64Data = Convert.ToBase64String(sirket.Logo);
                    imgDataURL = string.Format("data:image/png;base64,{0}", imgBase64Data);
                    ViewBag.ImageData = imgDataURL;
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error.");
                }
            }

            if (sirket == null)
            {
                return HttpNotFound();
            }
            return View(sirket);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(apiBaseAddress);

                var httpResponse = await client.DeleteAsync($"Sirket/{id}");
                if (httpResponse.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                    ModelState.AddModelError(string.Empty, "Kullanıcılar tarafından referans edilen şirket silinemez."); //TO-DO: Bu kısıma daha efektif bir çözüm getirilecek.
            }
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateSirketViewModel sirketResource)
        {
            //TO-DO: Yüklenen resimler kırpılacak. Veya yükleme kısmında Javascrip ile validasyon yapılabilir.
            var file = Request.Files["Image"];
            if (file != null)
            {
                byte[] fileBytes = new byte[file.ContentLength];
                file.InputStream.Read(fileBytes, 0, file.ContentLength);
                sirketResource.Logo = fileBytes;
            }
            else
            {
                // ... error handling here
            }

            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(apiBaseAddress);

                    var httpResponse = await client.PostAsJsonAsync("Sirket", sirketResource);
                    if (httpResponse.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Server error.");
                    }
                }
            }
            return View(sirketResource);
        }
    }

}

N-Tier.MiniApp.Presentation.WebUI/Views/Sirketler/Create.cshtml
@model N_Tier.MiniApp.Presentation.WebUI.ViewModels.CreateSirketViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create","Sirketler",FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>CreateSirketViewModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.SirketAdi, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SirketAdi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SirketAdi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Unvan, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Unvan, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Unvan, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Adres, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Adres, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Adres, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Logo, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="Image" required>
        </div>
    </div>

    @*<div class="form-group">
        @Html.LabelFor(model => model.Logo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Logo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Logo, "", new { @class = "text-danger" })
        </div>
    </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

N-Tier.MiniApp.Presentation.WebUI/Views/Sirketler/Delete.cshtml
@model N_Tier.MiniApp.Presentation.WebUI.ViewModels.SirketViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SirketViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SirketAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SirketAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Unvan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Unvan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logo)
        </dt>

        <dd>
            <img src="@ViewBag.ImageData">
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

N-Tier.MiniApp.Presentation.WebUI/Views/Sirketler/Details.cshtml
@model N_Tier.MiniApp.Presentation.WebUI.ViewModels.SirketViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>SirketViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SirketAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SirketAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Unvan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Unvan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logo)
        </dt>

        <dd>
            <img src="@ViewBag.ImageData">
        </dd>



    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

N-Tier.MiniApp.Presentation.WebUI/Views/Sirketler/Edit.cshtml
@model N_Tier.MiniApp.Presentation.WebUI.ViewModels.SirketViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Sirketler", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>SirketViewModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.SirketAdi, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SirketAdi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SirketAdi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Unvan, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Unvan, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Unvan, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Adres, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Adres, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Adres, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Logo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <img src="@ViewBag.ImageData">

        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Logo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="Image" required>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

N-Tier.MiniApp.Presentation.WebUI/Views/Sirketler/Index.cshtml
@model IEnumerable<N_Tier.MiniApp.Presentation.WebUI.ViewModels.SirketViewModel>
    @using N_Tier.MiniApp.Presentation.WebUI.Utilities

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SirketAdi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Unvan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Adres)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Logo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SirketAdi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Unvan)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Adres)
        </td>
        <td>
            @Html.Image(item.Logo)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id  }) |
            @Html.ActionLink("Details", "Details", new {  id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new {  id=item.Id })
        </td>
    </tr>
}

</table>